### ISSUE TITLE
Remove hardcoded paths from the QuickTranslate project

### ISSUE THREAD

**Issue by sabuncumurat** [roblatour/ARulerForWindows#1]
There are hardcoded paths embedded into the QuickTranslate project.  Following is an example:

https://github.com/roblatour/ARulerForWindows/blob/46764a961ab1558acd41c2dd618bb920067ddd4f/QuickTranslate/QuickTranslate/Module1.vb#L9

This makes the project difficult if not impossible to run on a system other than the one where it was developed.

I was lucky that I already had an "E:" disk on my system, and created a "Documents" folder under it, but it's not ideal.

FYI.

**Comment by roblatour** [comment]
Yes, the readme.md file for QuickTranslate says:

> The source for QuickTranslate is available as Open Source (MIT), and will need to be update to work on your Computer based on your file structures

https://github.com/roblatour/ARulerForWindows/blob/46764a961ab1558acd41c2dd618bb920067ddd4f/QuickTranslate/README.md

Regardless, I will see if I can update this to use relative paths - but if I do where you will run it from will be important.

**Comment by roblatour** [comment]
The QuickTranslate program source code has now been updated so that it can be run with relative paths
Note, the program assumes the file structure within this repo - i.e. the relative locations of the A Ruler For Windows (eruler) directory, the QuickTranslate directory, and the Localization Working Files directory remain the same.   Also updated was the associated README files.  Hope this make it easier for people.

**Comment by sabuncumurat** [comment]
Fast turnaround! :)
Now let's rewrite the repo in C#?
